{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"asyncTest called without async flag\" }\n    at ../../test262/harness/asyncHelpers.js:19\n    at asyncTest (../../test262/test/harness/asyncHelpers-throwsAsync-same-realm.js:11)\n\n","path":"../../test262/test/harness/asyncHelpers-throwsAsync-same-realm.js"}