{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"asyncTest called without async flag\" }\n    at ../../test262/harness/asyncHelpers.js:19\n    at asyncTest (../../test262/test/built-ins/Array/fromAsync/non-iterable-with-thenable-awaits-once.js:12)\n\n","path":"../../test262/test/built-ins/Array/fromAsync/non-iterable-with-thenable-awaits-once.js"}