{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a [object Test262Error] to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at anonymous (../../test262/test/built-ins/Object/prototype/__lookupSetter__/key-invalid.js:19)\n\n","path":"../../test262/test/built-ins/Object/prototype/__lookupSetter__/key-invalid.js"}