{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"a.concat() throws a Test262Error exception Expected a Function to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at anonymous (../../test262/test/built-ins/Array/prototype/concat/create-ctor-poisoned.js:24)\n\n","path":"../../test262/test/built-ins/Array/prototype/concat/create-ctor-poisoned.js"}