{"status":"FAIL","msg":"FAIL:\n Uncaught: { \"name\": \"Test262Error\", \"message\": \"obj should have an own property cause\" }\n    at assert (../../test262/harness/assert.js:18)\n    at verifyProperty (../../test262/harness/propertyHelper.js:63)\n    at ../../test262/test/built-ins/AggregateError/cause-property.js:31\n\n","path":"../../test262/test/built-ins/AggregateError/cause-property.js","memory_kb":11008,"duration":338597411}