{"status":"FAIL","msg":"FAIL:\n Uncaught: { name: \"Test262Error\", message: \"Expected a Test262Error to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at ../../test262/test/built-ins/Reflect/defineProperty/return-abrupt-from-attributes.js:25\n\n","path":"../../test262/test/built-ins/Reflect/defineProperty/return-abrupt-from-attributes.js","memory_kb":0,"duration":103878649}