{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a Function to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at anonymous (../../test262/test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T4.js:74)\n\n","path":"../../test262/test/built-ins/Array/prototype/toString/S15.4.4.2_A1_T4.js"}